### ISSUE TITLE
这个开源协议看起来很棒，但法律效力呢？

### ISSUE THREAD

**Issue by FurryR** [qwq233/License#2]
如题，我不懂法律，不太清楚这样授权是否真的有用。

**Comment by qwq233** [comment]
你为什么会认为没有法效?

**Comment by FurryR** [comment]
参见 https://opensource.stackexchange.com/questions/230/can-i-create-my-own-license-by-modifying-an-existing-one
另，因为语言和术语不同，除非聘请律师，否则无法确认这个协议和 GPL 系以及 CC-BY-SA 4.0 协议的兼容性。

**Comment by FurryR** [comment]
note: 这个讨论或许应该被移动到 discussion 但这个 repo 没有支持。

**Comment by qwq233** [comment]
显然它不与gpl兼容，因为它不允许商用
一个冷知识: 即使是WTFPL，也是有法律效应的

**Comment by FurryR** [comment]
> 显然它不与gpl兼容，因为它不允许商用 一个冷知识: 即使是WTFPL，也是有法律效应的

这里的兼容性指的并不是它能否被「GPL 系」开源项目使用，而是指以这个开源协议发行的开源项目能否使用「GPL 系」开源项目依赖。（提出这一点是因为语言差异可能导致部分术语不一，或者细节不一样，不能完全确保兼容性。）
我最近在做的一些项目可能被用于利益相关，应该要变更到这个协议。非常感谢你的时间。

**Comment by qwq233** [comment]
> > 显然它不与gpl兼容，因为它不允许商用 一个冷知识: 即使是WTFPL，也是有法律效应的
> 
> 这里的兼容性指的并不是它能否被「GPL 系」开源项目使用，而是指以这个开源协议发行的开源项目能否使用「GPL 系」开源项目依赖。（提出这一点是因为语言差异可能导致部分术语不一，或者细节不一样，不能完全确保兼容性。） 我最近在做的一些项目可能被用于利益相关，应该要变更到这个协议。非常感谢你的时间。

我这个是参照CC协议捏的，而CC协议很大程度是根据大陆法系制定的，可能和欧美法系有所冲突，能否使用GPL库你可能要自行判断。
